### PR TITLE
Authorization header fix

### PR DESCRIPTION
**Pull request by antalov**

### CODE REVIEW

**Comment by antalov** [comment]
CLA signed.

**Comment by karmi** [comment]
Hi @antalov, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/logstash-plugins/logstash-filter-kubernetes_metadata/pull/5.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by antalov** [comment]
@karmi Sorry, I missed it. It should be ok now.

**Comment by jsvd** [comment]
I am not familiar with this code and I see no tests confirm that this fixes an issue. Can I get someone else to verify this fixes the use of auth token?

**Comment by antalov** [comment]
@jsvd I see. You can look into [documentation](http://www.rubydoc.info/gems/rest-client/RestClient/Resource). Anyway, I doubt that someone is able use this plugin with bug like this. However, we are not going to use this plugin, so I don't necessarily need it fixed. You can close it if you want.

**Comment by jsvd** [comment]
@antalov thanks for the response. I should have taken a closer look at the patch, as the issue isn't about kubernetes but just basic usage of the rest client ruby class. LGTM

**Pull request merged**
